/*
 * This source file was generated by the Gradle 'init' task
 */
package org.APCSLowell;

public class GoogleBillboard {
    public boolean isPrime(long n) {
        if(n <= 1){
            return false;
        }
  
        for (int i = 2; i <=Math.sqrt(n); i++)
        {
            if (n % i == 0) 
                return false;
        }
        return true;
    }
    public long firstPrimeNumberIn(String n) {
        for(int i = 0; i <= n.length()-10; i++){
            long firstPrime = Long.parseLong(n.substring(i,i+10));
            boolean isPrime = true;

            if(firstPrime < 2) isPrime = false;

            for(int k = 2; k <= Math.sqrt(firstPrime); k++){
                if(firstPrime % k == 0){
                    isPrime = false;
                    break;
                }
            }

            if(isPrime){
                return firstPrime;
            }
        }
        return -1;
    }
}
