/*
 * This source file was generated by the Gradle 'init' task
 */
package org.APCSLowell;

public class GoogleBillboard {
    public boolean isPrime(long n) {
        if(n <= 1){
            return false;
        }
  
        for (int i = 2; i <=Math.sqrt(n); i++)
        {
            if (n % i == 0) 
            return false;
        }
        return true;
    }
    public long firstPrimeNumberIn(String n) {
        Long firstPrime;
        for(int i = 0; i < n.length()-2; i++){
            firstPrime = Long.parseLong(n.substring(i,i+2));
            for (int k = 2; k <=Math.sqrt(firstPrime); k++)
            {
                if (firstPrime % k != 0) 
                return firstPrime;
            }
  }
        return -1;
    }
}
